// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Two present mods the graph marks incompatible.
 *
 * `hard` is the declaration's own intensity (#129): the loader refuses to run
 * the two together, as against an author advising against it. An edge that
 * somehow carries no severity reads as hard -- an incompatibility of unknown
 * intensity is the one to show, not the one to quietly play down.
 */
export type ActiveConflict = { a: string, b: string, hard: boolean, source: string, };
