// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Two present mods the graph marks incompatible. `breaks` distinguishes the
 * harder `breaks` kind from a plain `conflicts`.
 */
export type ActiveConflict = { a: string, b: string, breaks: boolean, source: string, };
