// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Display } from "./Display";
import type { Source } from "./Source";

export type AssetEntry = { dest: string, sha1: string, size_bytes: number, required: boolean, source: Source, display: Display | null, };
