// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in the system-wide audit log: who did what, when.
 */
export type AuditRow = { id: number, actor_uid: number, actor_login: string, action: string, target?: string, detail?: string, created_at: number, };
