// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pack ids that carry editable authoring inputs (a config.json under
 * `packs/<id>/authoring/`), including packs not yet built. Admin-only:
 * authoring inputs are not part of the public read API.
 */
export type AuthoringPacksListing = { schema_version: number, packs: Array<string>, };
