// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Auth precondition the launcher enforces before spawning the game: which
 * provider the user must be signed in with, and (for SmartyCraft-bound
 * content) which SC game server the join + session bind to. Optional and
 * additive -- a manifest without it launches with no auth precondition.
 * `kind` is an open vocabulary the launcher matches (`smartycraft`,
 * `microsoft`, `both` today); unknown kinds are advisory, never blocking.
 */
export type AuthSpec = { kind: string, 
/**
 * The SC game-server id the join binds to (e.g. `Industrial`); absent
 * for providers with no SC join.
 */
server_id?: string, };
