// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One mod shipped by a build, resolved to the artifact the operator would
 * re-add (sha1) plus the human metadata to show it.
 */
export type BuildModRow = { name: string, version: string, sha1: string, filename: string, size_bytes: number, required: boolean, default_enabled: boolean, targets: Array<string>, mc_versions: Array<string>, };
