// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The pre-publish check, as the published build records it.
 *
 * A build is resolved against the registry graph before it is written. Two
 * findings mean the pack cannot start -- a declared hard dependency nothing
 * satisfies, and an artifact no loader in the pack can run -- and those stop
 * the publish. The rest are recorded rather than enforced: an active conflict may be
 * deliberate, a version outside a declared window usually runs anyway, and an
 * unidentified jar means the check was partial rather than clean.
 *
 * Recorded on the manifest because that is the artifact of a build; a job log
 * is in memory and its snapshot outlives nothing. Advisory to a launcher --
 * nothing here changes what gets installed.
 *
 * On a published manifest, a non-empty `blocking` means the build went out
 * over the gate, and `overridden` says so explicitly; a preview manifest
 * carries the same findings unoverridden, since nothing was published. Who
 * overrode it is not here: the actor lives in the job log and the audit trail,
 * which are behind the panel, and this file is public.
 */
export type BuildChecks = { blocking?: Array<string>, advisory?: Array<string>, overridden?: boolean, };
