// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One published build in the registry browser (the mirror hosts builds too, not
 * just loose mods).
 */
export type BuildSummary = { pack_id: string, pack_version: string, mc_version: string, loader_id: string | null, loader_version: string | null, java_major: number | null, is_latest: boolean, mod_count: number, };
