// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheInventoryEntry } from "./CacheInventoryEntry";

export type CacheInventory = { schema_version: number, generated_at: string, entries: Array<CacheInventoryEntry>, };
