// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheUse } from "./CacheUse";

export type CacheUsageEntry = { sha1: string, size_bytes: number, 
/**
 * Every (pack, filename) referencing this sha1 via an smrt_cache source.
 * Empty = orphan: on disk but no pack pulls it.
 */
uses: Array<CacheUse>, };
