// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheUsageEntry } from "./CacheUsageEntry";

/**
 * Admin-only cache inventory enriched with where each jar is used. The public
 * inventory stays lean (sha1 + size); usage cross-references authoring configs,
 * which are not part of the public read API. A jar with no uses is an orphan.
 */
export type CacheUsageListing = { schema_version: number, entries: Array<CacheUsageEntry>, };
