// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A capability more than one present mod provides.
 */
export type CapabilityOverlap = { capability: string, mods: Array<string>, };
