// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What moved on a row that is in both configs. Named rather than inferred from
 * which of `from`/`to` are present: a view that has to guess renders "edited"
 * for everything it does not recognise, and "edited" is what the old list said
 * where it should have said "renamed".
 */
export type ChangeField = "pin" | "default_enabled" | "required" | "filename" | "slug" | "display" | "value";
