// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which part of the config a row belongs to.
 */
export type ChangeGroup = "pack" | "mods" | "assets";
