// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigChange } from "./ConfigChange";

/**
 * Two states of one pack, and every difference between them.
 */
export type CommitDiff = { 
/**
 * The left side: a commit id, the literal `live`, or absent on a first
 * commit, which has nothing before it.
 */
from?: string, 
/**
 * The right side: always the commit named in the path.
 */
to: string, changes: Array<ConfigChange>, };
