// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line of the log: the commit, and which published builds came out of it.
 *
 * A checkpoint nobody shipped and one that is running on three hundred
 * machines look the same in a list of messages. The manifests already record
 * the commit they were built from; this is that record read back.
 */
export type CommitLogEntry = { 
/**
 * Pack versions built from this commit, newest first. Empty for a
 * checkpoint that was never published.
 */
builds: Array<string>, 
/**
 * Content address over everything below plus the snapshot.
 */
id: string, 
/**
 * The commit this one follows. Absent only on a pack's first commit.
 */
parent?: string, 
/**
 * Who pressed it. One name, because one person declared it.
 */
author: string, message: string, 
/**
 * RFC 3339, UTC.
 */
at: string, 
/**
 * `edit_rev` of the snapshot, so "has anything changed since?" is a string
 * comparison against the live config rather than a structural walk.
 */
config_rev: string, 
/**
 * Everyone whose saved work this commit takes in, the author included.
 *
 * The state is shared and merges live, so there are no separate change
 * sets to divide between people: whoever presses it signs it, and everyone
 * who saved since the last commit is named in it. Naming them here rather
 * than deriving it later is what makes attribution a record of what
 * happened instead of a guess made afterwards.
 */
contributors: Array<string>, };
