// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackSummary } from "./PackSummary";

/**
 * A published community pack for the public Community listing: the pack summary
 * plus the owner's GitHub login (resolved from the uid) for the `by <user>`
 * byline. Community packs are browseable on the site but never in the launcher's
 * official `/v1/packs` catalog.
 */
export type CommunityPack = { summary: PackSummary, owner_login: string, };
