// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One declared checkpoint. The snapshot it refers to lives beside it; this is
 * what the log shows and what a build records.
 */
export type Commit = { 
/**
 * Content address over everything below plus the snapshot.
 */
id: string, 
/**
 * The commit this one follows. Absent only on a pack's first commit.
 */
parent?: string, 
/**
 * Who pressed it. One name, because one person declared it.
 */
author: string, message: string, 
/**
 * RFC 3339, UTC.
 */
at: string, 
/**
 * `edit_rev` of the snapshot, so "has anything changed since?" is a string
 * comparison against the live config rather than a structural walk.
 */
config_rev: string, 
/**
 * Everyone whose saved work this commit takes in, the author included.
 *
 * The state is shared and merges live, so there are no separate change
 * sets to divide between people: whoever presses it signs it, and everyone
 * who saved since the last commit is named in it. Naming them here rather
 * than deriving it later is what makes attribution a record of what
 * happened instead of a guess made afterwards.
 */
contributors: Array<string>, };
