// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Commit } from "./Commit";
import type { ConfigChange } from "./ConfigChange";

/**
 * What the panel needs to decide whether a commit is worth offering: where the
 * history is now, and whether the live config has moved off it.
 */
export type CommitStatus = { 
/**
 * The newest commit, absent on a pack that has never committed.
 */
head?: Commit, 
/**
 * What a commit would record: every difference between `head`'s snapshot
 * and the live config, as rows. Empty on a pack with no history -- there is
 * nothing to compare against, and `uncommitted` says so on its own.
 */
changes: Array<ConfigChange>, 
/**
 * How many of them there are. Zero means the working state is exactly the
 * last checkpoint, which is the only state in which a build needs no new
 * commit. It is the length of `changes` wherever there is a `head` to
 * compare against, so a number can never disagree with the list beside it;
 * on a pack that has never committed it is 1 with nothing listed, because
 * the outstanding change is the pack itself and there is nothing to
 * compare it against.
 */
uncommitted: number, 
/**
 * Who has saved since `head`, so the commit dialog can name them before it
 * is pressed rather than after.
 */
pending_authors: Array<string>, };
