// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Commit } from "./Commit";

/**
 * What the panel needs to decide whether a commit is worth offering: where the
 * history is now, and whether the live config has moved off it.
 */
export type CommitStatus = { 
/**
 * The newest commit, absent on a pack that has never committed.
 */
head?: Commit, 
/**
 * Fields that differ between the live config and `head`'s snapshot. Zero
 * means the working state is exactly the last checkpoint, which is the
 * only state in which a build needs no new commit.
 */
uncommitted: number, 
/**
 * Who has saved since `head`, so the commit dialog can name them before it
 * is pressed rather than after.
 */
pending_authors: Array<string>, };
