// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeField } from "./ChangeField";
import type { ChangeGroup } from "./ChangeGroup";
import type { ChangeOp } from "./ChangeOp";

/**
 * One difference between two configs.
 */
export type ConfigChange = { group: ChangeGroup, op: ChangeOp, 
/**
 * The row's identity within its group (`m:<project>`, `s:<slug>`,
 * `f:<filename>`, an asset's `dest`, or a pack field's name). Stable across
 * a re-pin and a rename, so a view can key a row by it and follow it.
 */
key: string, 
/**
 * What to call the row on screen: a filename, an asset destination, or the
 * pack field's own name.
 */
label: string, 
/**
 * Which aspect moved; absent on an arrival or a departure.
 */
field?: ChangeField, from?: string, to?: string, 
/**
 * The Modrinth project behind the row, when it has one. A pin is a version
 * id on the wire (`sc43sMLj -> bqMxf6Ua`), which tells a reader nothing;
 * the project is what lets a view fetch the version numbers and show those
 * instead. Carried rather than resolved here: the diff must not wait on
 * Modrinth to answer what changed.
 */
project?: string, };
