// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DropAssets } from "./DropAssets";
import type { ExtraAsset } from "./ExtraAsset";
import type { ExtraMod } from "./ExtraMod";
import type { GenerateConfig } from "./GenerateConfig";
import type { PackMeta } from "./PackMeta";
import type { SubstituteEntry } from "./SubstituteEntry";

/**
 * All-in-one curator file. Single TOML that drives a deterministic
 * chain of mutations on a [`PackConfig`] via [`apply_curator`].
 *
 * Daily workflow for a SC-derived pack:
 *   1. `smrt-pack bootstrap` (SC zip -> starter PackConfig)
 *   2. `smrt-pack apply-curator --curator curator.toml`
 *   3. `smrt-pack build --curator curator.toml`
 *
 * The individual passes ([`enrich_from_mcmod_info`],
 * [`apply_role_table`], [`infer_requires_from_mcmod_info`]) remain
 * callable from their own subcommands for power-user / debugging
 * scenarios, but the canonical pipeline goes through this one file.
 */
export type Curator = { pack_meta: PackMeta, substitute: { [key in string]?: SubstituteEntry }, extra_mods: Array<ExtraMod>, extra_assets: Array<ExtraAsset>, drop_assets: DropAssets, generate: GenerateConfig, };
