// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Display } from "./Display";
import type { SourceDecl } from "./SourceDecl";

export type DeclaredAsset = { dest: string, required: boolean, source: SourceDecl, display?: Display, note?: string, };
