// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Display } from "./Display";
import type { SourceDecl } from "./SourceDecl";

export type DeclaredMod = { filename: string, required: boolean, 
/**
 * Install-time default for an optional mod; the curator's default-off list
 * flips it. Carried into the emitted ModEntry.
 */
default_enabled: boolean, source: SourceDecl, display?: Display, 
/**
 * Curator-assigned stable identity, carried into the emitted ModEntry so the
 * launcher can key an optional mod's toggle by it across version bumps (ADR
 * 0002). Optional; a Modrinth mod already has a stable key in its project id.
 */
slug?: string, };
