// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Display } from "./Display";
import type { SourceDecl } from "./SourceDecl";

export type DeclaredMod = { filename: string, 
/**
 * Install-time default: whether the mod ships enabled. Every mod is toggleable
 * -- there is no hand-set "required" flag. A mod another present mod hard-depends
 * on is marked required on the emitted ModEntry automatically at build time.
 */
default_enabled: boolean, source: SourceDecl, display?: Display, 
/**
 * Curator-assigned stable identity, carried into the emitted ModEntry so the
 * launcher can key an optional mod's toggle by it across version bumps (ADR
 * 0002). Optional; a Modrinth mod already has a stable key in its project id.
 */
slug?: string, 
/**
 * True when depfill appended this entry as a resolved hard dependency
 * (server-managed), false for curator-declared mods. A pulled entry is
 * sticky: a save whose body lacks it merges it back in (a client that
 * never saw it must not delete it), and it is dropped only when no
 * curator-declared mod still reaches it through hard requires edges.
 */
pulled: boolean, };
