// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry present on only one side of the diff.
 */
export type DiffEntry = { filename: string, 
/**
 * Version label where the registry knows the artifact; the handler fills
 * it, the pure diff leaves it absent.
 */
version?: string, };
