// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry present on both sides whose artifact changed.
 */
export type DiffUpdate = { 
/**
 * The `to` side's filename (the one an updated instance ends up with).
 */
filename: string, version_from?: string, version_to?: string, sha1_from: string, sha1_to: string, };
