// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An entry whose install-time default flipped (content unchanged).
 */
export type DiffToggle = { filename: string, default_enabled_from: boolean, default_enabled_to: boolean, };
