// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PresenceClass } from "./PresenceClass";
import type { Requirement } from "./Requirement";

/**
 * Advisory display metadata for launcher UIs. Adding or removing this
 * block on an existing manifest is forward-compatible -- the wire schema
 * version stays at 2. Clients that don't recognise the block fall back
 * to defaults derived from `filename` / `dest`.
 *
 * `icon_url`, `role`, and `requires` are additive launcher-side richer
 * UX hooks (per-item icons, role-grouped pickers, dependency graph
 * rendering). All three optional; manifests without them parse cleanly
 * on every client that reached the v2 schema.
 */
export type Display = { name?: string, description?: string, category?: string, incompatible_with: Array<string>, 
/**
 * SPDX license identifier where known (e.g. "MIT", "LGPL-3.0-only",
 * "CC-BY-NC-SA-3.0"). Useful for a launcher to surface
 * non-redistributable mods to the user. Absent for proprietary mods
 * without an SPDX-compatible declaration.
 */
license?: string, 
/**
 * Source / project / wiki URL. Used by a launcher's "Learn more"
 * affordance. Preferred order: mcmod.info url, Modrinth source_url,
 * CurseForge project page.
 */
url?: string, 
/**
 * Per-item icon URL. Mirror serves directly for smrt_cache /
 * smrt_static entries; Modrinth-sourced entries can leave this null
 * and let the client resolve via the source's `project_id` against
 * the Modrinth API. Null = client falls back to a letter avatar.
 */
icon_url?: string, 
/**
 * Short tag for grouping interchangeable mods. Launcher renders all
 * mods with the same role as a single selectable slot ("Recipe
 * viewer: JEI [v]" with REI / JER / EMI alternatives). Canonical
 * values are mirror-curated; the launcher does not enumerate them.
 */
role?: string, 
/**
 * Same-manifest dependency declarations. Each entry's `filename`
 * points at another mod in this pack's `mods[]`. Resolver
 * validates the reference at install time; missing references
 * surface as a warning rather than a hard failure.
 */
requires: Array<Requirement>, 
/**
 * Presence class of the entry in this pack (required / optional_client /
 * optional_server / optional_both / coremod), computed at build from the
 * side+policy classification and the dependency graph. Advisory like the
 * rest of the block: `ModEntry.required` stays the enforcing flag, and the
 * two are consistent by construction. Absent = unclassified (and on every
 * manifest built before the field landed).
 */
presence?: PresenceClass, };
