// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Asset destinations the curator wants stripped from the
 * emitted manifest. Use case: SC's archive ships ~80 mod-default
 * config files (foamfix.cfg, chisel.cfg, AE2's items.csv dump,
 * stale CoFH world JSONs, etc) that every Forge mod regenerates
 * from its own jar resources on first launch. Shipping the
 * defaults pre-baked locks every install into "SC's choice =
 * mod default" and means mod updates that introduce new config
 * fields cannot evolve cleanly. The drop pass runs in
 * `apply-curator` and removes matching entries from
 * [`PackConfig::assets`] before [`build`] writes the manifest.
 *
 * Paths match the asset `dest` field byte-for-byte (no glob, no
 * regex). One entry per file. Modrinth-sourced assets (extra
 * shaderpacks, resourcepacks) are never matched even if their
 * dest accidentally collides -- the filter keys on
 * `source.type == "smrt_static"` to keep curator extras safe.
 */
export type DropAssets = { paths: Array<string>, };
