// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackManifest } from "./PackManifest";
import type { PackSummary } from "./PackSummary";

/**
 * What a dry-run build computes without publishing: the resolved manifest the
 * launcher would download, plus the summary card it would show. Stashed on the
 * job so the panel can render a launcher-faithful preview and diff it against
 * the currently-published manifest.
 */
export type DryRun = { manifest: PackManifest, summary: PackSummary, };
