// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtraAssetKind } from "./ExtraAssetKind";

/**
 * Modrinth-direct extra asset (resourcepack / shaderpack / data pack).
 * `dest_dir` is the destination subfolder ("resourcepacks",
 * "shaderpacks", etc); the resolved filename appends to that path.
 */
export type ExtraAsset = { slug: string, dest_dir: string, modrinth_kind: ExtraAssetKind, required: boolean, category: string | null, description: string | null, name_override: string | null, };
