// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Modrinth-direct extra mod the curator wants to add on top of the
 * SC-derived pack. The build pipeline does the Modrinth API lookup
 * at apply time to resolve project_id + version_id + primary file.
 */
export type ExtraMod = { slug: string, required: boolean, category: string | null, description: string | null, name_override: string | null, };
