// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Featured = { schema_version: number, generated_at: string, featured_servers: Array<string>, featured_packs: Array<string>, };
