// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A declared hard edge that would force-install a client-side mod.
 */
export type ForcedClientEdge = { 
/**
 * The client-side mod being forced.
 */
filename: string, 
/**
 * The declaring mods.
 */
needed_by: Array<string>, 
/**
 * Provenance of the offending edge (jar-meta / modrinth / authored / curator).
 */
source: string, };
