// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One Minecraft version as Modrinth indexes it. `version_type` separates a
 * release from a snapshot, which is the difference between what a pack is
 * normally built against and what almost nothing is mirrored for.
 */
export type GameVersion = { version: string, version_type: string, date: string, 
/**
 * Modrinth's own marker for a version worth showing first in a picker.
 */
major: boolean, };
