// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Auto-generated artefacts that land in the pack's static area as
 * part of `apply-curator` and become regular `smrt_static` assets in
 * the resulting manifest. Each generator is gated by a boolean so
 * curator opts in per pack.
 */
export type GenerateConfig = { 
/**
 * Emit `<static>/<filename>` listing the curator-authored
 * `(lowercase_modid, claimed_version)` pairs verbatim. Adds a
 * matching `smrt_static` asset entry so the launcher syncs the
 * file into `<clientDir>/<filename>`. The hidemymods coremod
 * reads it at FML handshake time to spoof SC's required
 * modlist.
 *
 * CRITICAL: the entries below describe what SC's SERVER
 * expects, NOT what our pack actually ships. Hivens-rework
 * packs are already divergent from SC canonical (extra cozy
 * mods, library swaps, OSN replacing Smarty); auto-extract
 * from our jars produces the WRONG spoof (SC would receive
 * our versions instead of its expected ones, and the handshake
 * would reject). Source of truth is SC's wire ModList,
 * captured once per SC update and pasted here.
 */
hidemymods: boolean, 
/**
 * Filename inside the static dir. Default
 * `hidemymods-spoof.json` matches the launcher-side convention
 * the hidemymods coremod reads from `<clientDir>/`.
 */
hidemymods_filename: string, 
/**
 * The actual spoof table: `lowercase_modid -> claimed_version`.
 * Curator-authored from SC's wire ModList; reproduced verbatim
 * in the emitted JSON. Values like `"$version"` (SC's literal
 * placeholder for `nbtedit`) round-trip byte-for-byte.
 */
hidemymods_entries: { [key in string]?: string }, };
