// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One (Minecraft version, loader) world the registry actually holds, and how many
 * artifacts sit in it. The panel offers these as the graph's slice choices and
 * opens on the busiest, rather than inventing a combination nothing matches (#49).
 */
export type GraphSlice = { mc_version: string, loader: string, artifacts: number, };
