// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One node in the dependency/conflict graph view: a mod that is an endpoint of
 * at least one relation. `name` is resolved server-side (canonical -> slug ->
 * modid -> `#id`); `modrinth` flags a Modrinth-identified mod so the view can
 * mark genuine identities apart from bare-modid ones.
 */
export type GraphNode = { mod_id: number, name: string, modid?: string, modrinth: boolean, };
