// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One edge in the graph. `to_mod_id` is the resolved target when the selector
 * names a mod the registry knows; `None` marks an external/unresolved target
 * (a modid not harvested, or a `provides` capability), which the view renders
 * as a labelled leaf so the dangling requirement is still visible. `kind` and
 * `source` are the relation vocab strings.
 */
export type GraphEdge = { from_mod_id: number, to_mod_id?: number, target: string, kind: string, source: string, };
