// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphEdge } from "./GraphEdge";
import type { GraphNode } from "./GraphNode";

/**
 * The whole relation graph for the read-only view + node editor.
 */
export type GraphData = { nodes: Array<GraphNode>, edges: Array<GraphEdge>, };
