// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The entries that differ between a repackaged jar and its genuine counterpart.
 */
export type JarDiff = { 
/**
 * Same path, different bytes, `.class` -- the tamper that matters.
 */
changed_classes: Array<string>, 
/**
 * Same path, different bytes, not a class -- usually reformatting noise.
 */
changed_resources: Array<string>, 
/**
 * Present only in the repackaged jar.
 */
added: Array<string>, 
/**
 * Present only in the genuine jar.
 */
removed: Array<string>, 
/**
 * Entries byte-identical in both (context for how much matched).
 */
identical: number, };
