// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A declared artifact built for loaders this pack does not run.
 *
 * A pack natively runs its own loader and everything that loader inherits from
 * (cleanroom runs forge's artifacts, quilt runs fabric's). Anything else needs a
 * bridge -- a connector mod that carries another loader's mods at runtime, which
 * the registry records as a `provides` of the `loader:<name>` capability.
 */
export type LoaderMismatch = { filename: string, 
/**
 * the loaders the artifact was actually published for
 */
artifact_loaders: Array<string>, pack_loader: string, 
/**
 * The present mod bridging one of those loaders, when there is one. A bridge
 * carries the mod -- what it does not promise is how stable the result is,
 * and that rides on the connector rather than on any one mod, so it is not
 * something this pass can judge per mod (and does not try to).
 */
bridged_by?: string, };
