// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A jar whose declared loader window the pack's pinned loader build falls
 * outside of -- JEI's `neoforge [21.1.238,)` under a pack pinned to
 * `21.1.234`. The loader reads that window out of the jar and refuses to
 * start, naming the jar; nothing says which build it wanted, or that the pin
 * is a line in this pack's own config.
 */
export type LoaderVersionIssue = { filename: string, 
/**
 * The loader both sides name, as the mirror spells it.
 */
loader: string, 
/**
 * The build this pack pins.
 */
pack_version: string, 
/**
 * The window the jar declares, verbatim.
 */
required_range: string, };
