// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoaderBuild } from "./LoaderBuild";

/**
 * A loader's builds, as the mirror last knew them.
 */
export type LoaderVersions = { loader: string, builds: Array<LoaderBuild>, fetched_at: string, fetched_unix: number, 
/**
 * Past its freshness window: a refresh is in flight behind this answer, or
 * upstream is not answering.
 */
stale: boolean, };
