// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a mod sits with the pack's loader. Deliberately not a boolean: the
 * registry models four different answers and flattening them would either hide
 * working mods or promise ones that cannot load.
 */
export type LoaderFit = "native" | "bridged" | "bridgeable" | "foreign" | "unknown";
