// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A declared artifact built for loaders this pack does not run.
 *
 * A pack natively runs its own loader and everything that loader inherits from
 * (cleanroom runs forge's artifacts, quilt runs fabric's). Anything else needs a
 * bridge -- a connector mod that carries another loader's mods at runtime, which
 * the registry records as a `provides` of the `loader:<name>` capability.
 */
export type LoaderMismatch = { filename: string, 
/**
 * the loaders the artifact was actually published for
 */
artifact_loaders: Array<string>, pack_loader: string, 
/**
 * The present mod bridging one of those loaders, when there is one. A bridge
 * is never a guarantee: it carries some of the other loader's mods and not
 * others, so a bridged artifact is reported as unverified and never as fine.
 */
bridged_by?: string, };
