// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One build of a loader.
 */
export type LoaderBuild = { version: string, 
/**
 * The Minecraft version this build is for, where the loader ties them
 * together (Forge, NeoForge). Absent for loaders whose builds are
 * independent of it -- Fabric and Quilt publish one loader for all of them.
 */
minecraft?: string, 
/**
 * Upstream's own "use this one" marker. Forge publishes it explicitly;
 * Fabric and Quilt call it stable.
 */
recommended: boolean, 
/**
 * Newest for its Minecraft version.
 */
latest: boolean, };
