// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManifestBuildInfo } from "./ManifestBuildInfo";

export type ManifestVersionsListing = { schema_version: number, pack_id: string, 
/**
 * The version `manifests/latest` currently points at; absent when the
 * pack has no published build.
 */
latest?: string, 
/**
 * Per-build metadata, newest first (ordered by `date_published`).
 */
builds: Array<ManifestBuildInfo>, };
