// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoaderSpec } from "./LoaderSpec";
import type { VersionChannel } from "./VersionChannel";

/**
 * One retained build of a pack, as the version picker sees it: the version
 * label plus the metadata a launcher needs to render and order a list of
 * builds without fetching each manifest. Field names follow the Modrinth
 * version object (`version_number` / `version_type` / `date_published`).
 */
export type ManifestBuildInfo = { version_number: string, 
/**
 * The manifest's stored channel; for manifests predating the field,
 * recovered from the legacy string rule (`SNAPSHOT-` prefix = beta).
 */
version_type: VersionChannel, 
/**
 * The manifest's `generated_at` (RFC 3339): when the build produced it.
 */
date_published: string, 
/**
 * The manifest's content fingerprint where present -- the reliable
 * "did the content change?" signal between two builds.
 */
fingerprint?: string, 
/**
 * The commit this build was made from (#122), where it names one. Absent
 * on CLI builds, which build the working config, and on every build from
 * before a pack had history. Carried in the listing so "which builds came
 * out of this checkpoint" is answerable without opening every manifest.
 */
built_from?: string, 
/**
 * Curator-authored release notes, where the build carries them.
 */
changelog?: string, 
/**
 * The same notes per language tag; see `PackManifest::changelog_i18n`.
 */
changelog_i18n?: { [key in string]: string }, mods_count: number, assets_count: number, 
/**
 * What this build runs on. Present per build rather than per pack because
 * a pack outlives its target: telling a player that an update moves them
 * from 1.12.2 to 1.20.1, or off Forge, is exactly what a version list is
 * read for, and answering it from the listing costs one request instead of
 * one manifest per build.
 */
minecraft_version: string, loader: LoaderSpec, 
/**
 * Every file this build lists, added up: what a fresh install downloads.
 * Optional entries are counted too -- what an individual player ends up
 * fetching depends on what they enable, and that answer only exists in the
 * manifest.
 */
size_bytes: number, };
