// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Axis B -- whether a mod must be present on both sides for a client to join
 * a server carrying it. Orthogonal to [`SideClass`]: a Both-side mod with
 * `acceptableRemoteVersions = "*"` / `displayTest = NONE` runs everywhere but
 * tolerates the other side lacking it.
 */
export type MatchPolicy = "must_match" | "tolerant";
