// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Subset of the 1.12.2-era Forge `mcmod.info` schema the curator
 * pipeline reads. Real-world files are mostly the array form
 * `[{...mod...}, ...]`; some older mods wrap a single object in
 * `{"modListVersion": 2, "modList": [{...}]}`. [`read_mcmod_info`]
 * flattens both into `Vec<McModInfo>`.
 */
export type McModInfo = { modid: string, name: string, version: string, description: string, url: string, dependencies: Array<string>, 
/**
 * 1.12-era Forge spells the author list `authorList`. Harvest reads it as a
 * local, network-free author source (falling back to Modrinth only when the
 * jar carries none).
 */
authorList: Array<string>, };
