// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameVersion } from "./GameVersion";

/**
 * A cached list, with the answer to "how old is this?" rather than only the
 * list -- a stale list is worth serving and worth admitting to.
 */
export type MinecraftVersions = { versions: Array<GameVersion>, 
/**
 * When the mirror last heard this from upstream (RFC 3339), for whoever is
 * reading the answer.
 */
fetched_at: string, 
/**
 * The same instant as a number, which is what freshness is measured
 * against. The mirror formats time and does not parse it anywhere, and a
 * parser earned for one comparison is more surface than one integer.
 */
fetched_unix: number, 
/**
 * This copy is past its freshness window: a refresh is in flight behind
 * the answer, or upstream is not answering. Either way it is old news, and
 * the panel says so rather than presenting it as current.
 */
stale: boolean, };
