// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something that happened to the mirror as a whole.
 */
export type MirrorEvent = { "kind": "registry", what: string, } | { "kind": "pack", pack_id: string, what: string, } | { "kind": "moderation", what: string, } | { "kind": "catalog", what: string, };
