// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A required target no present mod satisfies. `target` is the graph selector
 * (a modid, or `modrinth:<project_id>`); `needed_by` are the filenames that
 * require it; `source` is the provenance of the authoritative edge.
 */
export type MissingDep = { target: string, needed_by: Array<string>, version_range?: string, source: string, };
