// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A jar's `required` mixin config names a class that the pack's own copy of the
 * mod owning it does not have.
 *
 * Fatal, and invisible in every declaration: both mods that hit it declared an
 * open lower bound on the host, which every version satisfies. The loader
 * throws during init and blames whichever mod first reached the missing class,
 * so the crash report names a bystander.
 */
export type MixinGap = { 
/**
 * The jar whose mixin config asks for it.
 */
filename: string, 
/**
 * The config that declares it (`sable.mixins.json`).
 */
config: string, 
/**
 * The missing class, as a binary name.
 */
needed: string, 
/**
 * The pack's jar that owns the class's package and does not carry it.
 */
owner: string, };
