// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModEdge } from "./ModEdge";
import type { ModUse } from "./ModUse";
import type { ReleaseRow } from "./ReleaseRow";

/**
 * The aggregated read model behind one mod's page: identity, the facets across
 * its artifacts, its releases (files), the relations that touch it, and the pack
 * builds that ship it. Backs the public `GET /v1/mods/:id`; the same view serves
 * operators, who additionally reach the gated edit/diff endpoints.
 */
export type ModDetail = { mod_id: number, 
/**
 * canonical_name -> slug -> modid -> `#<id>`, resolved server-side.
 */
name: string, slug: string | null, author: string | null, modid?: string, modrinth_project_id?: string, 
/**
 * Modrinth project environment flags where known
 * (`required` | `optional` | `unsupported`); the priority-1 side source
 * for classification, surfaced verbatim like the project object's
 * `client_side` / `server_side`.
 */
client_side?: string, server_side?: string, loaders: Array<string>, mc_versions: Array<string>, releases: Array<ReleaseRow>, edges: Array<ModEdge>, 
/**
 * Pack builds that ship this mod. Filtered to official + published on the
 * public endpoint so a guest never learns a draft's name from it.
 */
used_by: Array<ModUse>, };
