// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One relation touching a mod, from that mod's page perspective. `dir` is "out"
 * (this mod -> other) or "in" (other -> this mod). `other_mod_id` is the
 * catalogued counterpart when the selector resolves; `None` marks an external
 * target (an uncatalogued modid or a `provides` capability), so the page can
 * render it as a plain label rather than a link.
 */
export type ModEdge = { dir: string, other_mod_id?: number, other_name: string, kind: string, source: string, };
