// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Display } from "./Display";
import type { Source } from "./Source";

export type ModEntry = { filename: string, sha1: string, size_bytes: number, required: boolean, 
/**
 * Install-time default for an optional entry (`required = false`): on unless
 * a curator opts it out. Omitted from the wire when true (the launcher's
 * SmrtModEntry defaults it to true), so only an opted-out mod carries it.
 */
default_enabled: boolean, source: Source, display?: Display, };
