// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoaderFit } from "./LoaderFit";

/**
 * One candidate to add, from either side.
 */
export type ModHit = { name: string, slug?: string, author?: string, description?: string, 
/**
 * The Modrinth project, when the mod is catalogued there -- what a pinned
 * declaration needs, and what the project icon is keyed by.
 */
modrinth_project_id?: string, 
/**
 * The registry's own id, when the mirror has harvested it.
 */
mod_id?: number, icon_url?: string, icon_sha1?: string, 
/**
 * True when the mirror holds bytes for this mod: the pack can declare a
 * cache source and the launcher never leaves the mirror for it.
 */
mirrored: boolean, fit: LoaderFit, 
/**
 * Which loader the bridge carries, when `fit` is bridged -- the fact worth
 * stating, since removing that one mod takes every mod riding it.
 */
bridged_from?: string, loaders: Array<string>, mc_versions: Array<string>, };
