// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A resolved display name for a Modrinth project the registry references but does
 * not host. The graph turns an external `modrinth:<id>` leaf into one of these so
 * it reads as "The Aether", not the opaque id. `id` is the project id (also the
 * map key on the client); `slug` is present when Modrinth returned one.
 */
export type ModrinthProjectName = { id: string, title: string, slug?: string, };
