// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One mod in the registry browser: identity, the human metadata an enriching
 * harvest fills in, and the facets aggregated across all its artifacts.
 */
export type ModSummary = { mod_id: number, 
/**
 * canonical_name -> slug -> modid -> `#<id>`, resolved server-side.
 */
name: string, slug: string | null, author: string | null, loaders: Array<string>, mc_versions: Array<string>, version_count: number, };
