// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Q1: a (pack build, version, filename) that ships a given mod.
 */
export type ModUse = { pack_id: string, pack_version: string, version: string, filename: string, };
