// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One thing that happened to somebody's discussion, as their own list shows it.
 *
 * It carries the thread's own words rather than a copy made when the event
 * happened: a title edited afterwards must not leave a stale line in somebody's
 * list saying something the thread no longer says.
 */
export type Notification = { id: number, 
/**
 * `comment` | `opened` | `settled`.
 */
kind: string, thread_id: number, pack_id: string, title: string, 
/**
 * The thread's standing now, which is what the reader is about to open.
 */
status: string, actor_uid: number, actor_login?: string, created_at: number, read: boolean, };
