// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pack-card metadata (icon / banner / gallery / long description) merged into
 * the emitted `summary.json` at build time. Every field optional; absent fields
 * stay out of summary.json (per the `skip_serializing_if` on PackSummary).
 */
export type PackMeta = { icon_url: string | null, banner_url: string | null, gallery_urls: Array<string>, description_md: string | null, };
