// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something that happened to a pack, as its editors see it.
 */
export type PackEvent = { "kind": "saved", rev: string, by: string, } | { "kind": "present", editors: Array<string>, } | { "kind": "doc", by: string, update: string, } | { "kind": "committed", id: string, by: string, message: string, };
