// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetEntry } from "./AssetEntry";
import type { AuthSpec } from "./AuthSpec";
import type { BuildChecks } from "./BuildChecks";
import type { JavaSpec } from "./JavaSpec";
import type { LoaderSpec } from "./LoaderSpec";
import type { MinecraftSpec } from "./MinecraftSpec";
import type { ModEntry } from "./ModEntry";
import type { VersionChannel } from "./VersionChannel";

export type PackManifest = { schema_version: number, pack_id: string, pack_version: string, 
/**
 * Release channel of this build (Modrinth `version_type` vocabulary),
 * stored -- the version string carries no channel semantics. Absent on
 * manifests built before the field landed; readers fall back to the
 * legacy string rule (`SNAPSHOT-` prefix = beta). Additive, so the
 * schema version stays at 2.
 */
channel?: VersionChannel, 
/**
 * Curator-authored release notes for this build (the Modrinth
 * `version.changelog` analog). CommonMark; absent when none were given.
 * The structural diff endpoint complements it -- this is the "why", the
 * diff is the "what".
 */
changelog?: string, 
/**
 * The same notes per language, keyed by a language tag (`en`, `ru`).
 *
 * `changelog` stays what a client reads when it can match nothing here, so
 * every existing client keeps working and nothing has to guess which
 * language an untagged string is written in -- the tagged map includes that
 * language too, and the untagged copy is the compatibility shim. Open by
 * design: a mirror serving a community that speaks neither of the panel's
 * own languages is the ordinary case for a self-hosted registry, not an
 * exception. Additive, so the schema version stays at 2.
 */
changelog_i18n?: { [key in string]: string }, generated_at: string, 
/**
 * Content fingerprint: a stable hash of what actually lands in an instance
 * (artifact hashes + install flags + loader/java/mc), independent of the
 * `pack_version` label and `generated_at`. Two builds with identical
 * content share a fingerprint; a launcher uses it as the reliable "did the
 * content change?" signal rather than trusting a hand-assigned version
 * bump. Additive (absent on manifests built before it landed; old clients
 * ignore it), so the schema version stays at 2.
 */
fingerprint?: string, 
/**
 * What the mirror knew about this build when it published it. Absent when
 * the pre-publish check found nothing to say (and on every manifest built
 * before the check landed), so the schema version stays at 2.
 */
checks?: BuildChecks, 
/**
 * The commit this build was made from (#122), so a published build is
 * reproducible: the config it came from is a stored snapshot rather than
 * whatever happened to be on screen at that instant. Absent on builds made
 * straight from the live config -- the CLI's `--config <file>`, and every
 * build made before history landed -- so the schema version stays at 2.
 */
built_from?: string, minecraft: MinecraftSpec, loader: LoaderSpec, java: JavaSpec, 
/**
 * See [`AuthSpec`]. Absent = no auth precondition.
 */
auth?: AuthSpec, mods: Array<ModEntry>, assets: Array<AssetEntry>, };
