// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackSummary } from "./PackSummary";

export type PackListing = { schema_version: number, generated_at: string, packs: Array<PackSummary>, };
