// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pack-level rich metadata authored by the curator in a TOML file.
 * Merged into the emitted `summary.json` by `smrt-pack build` when
 * passed via `--pack-meta`. Every field optional; absent fields stay
 * out of summary.json (per the `skip_serializing_if` on PackSummary).
 */
export type PackMeta = { icon_url: string | null, banner_url: string | null, gallery_urls: Array<string>, description_md: string | null, };
