// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Curation tier. `official` = the mirror's own packs (the launcher's catalog,
 * no personal byline); `community` = a member's pack. The launcher reads
 * official only.
 */
export type PackTier = "official" | "community";
