// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What somebody may do to one pack (ADR 0006). Declaration order is the rank
 * (`View < Edit < Own`), so a gate asks `level >= PackLevel::Edit` the way the
 * mirror-wide gate asks `role >= Role::Admin`.
 *
 * The owner of a community namespace and an admin are never stored as a level:
 * they are what the gate knows before it reads. A stored level is only ever the
 * third answer -- somebody who is neither.
 */
export type PackLevel = "view" | "edit" | "own";
