// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeclaredAsset } from "./DeclaredAsset";
import type { DeclaredMod } from "./DeclaredMod";
import type { LoaderSpec } from "./LoaderSpec";

/**
 * Admin-authored declaration of a pack. The build step turns this into a wire
 * `PackManifest` by resolving each source against Modrinth or the local
 * storage tree. Distinct from `PackManifest` because authoring does not
 * require admin to hand-write `sha1` and `size_bytes` for Modrinth sources --
 * those are looked up at build time.
 */
export type PackConfig = { pack_id: string, display_name: string, tagline: string, minecraft_version: string, loader: LoaderSpec, java_major: number, tags: Array<string>, featured: boolean, mods: Array<DeclaredMod>, assets: Array<DeclaredAsset>, };
