// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Somebody a pack's keepers have stopped from writing on it.
 *
 * The reason is written for the person it names: a door that shuts with no
 * word is one they can only argue with, while a refusal that says why is one
 * they can answer or accept. It is shown to them when they try to write, and
 * to whoever moderates the pack.
 */
export type PackBlock = { github_uid: number, 
/**
 * Absent for a uid that has never signed in here.
 */
login?: string, reason?: string, blocked_by: number, 
/**
 * Who decided it, by name where the mirror knows it.
 */
blocked_by_login?: string, blocked_at: number, };
