// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetEntry } from "./AssetEntry";
import type { JavaSpec } from "./JavaSpec";
import type { LoaderSpec } from "./LoaderSpec";
import type { MinecraftSpec } from "./MinecraftSpec";
import type { ModEntry } from "./ModEntry";

export type PackManifest = { schema_version: number, pack_id: string, pack_version: string, generated_at: string, minecraft: MinecraftSpec, loader: LoaderSpec, java: JavaSpec, mods: Array<ModEntry>, assets: Array<AssetEntry>, };
