// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Somebody a pack's keepers have stopped from writing on it.
 *
 * The reason is the keepers' note to themselves and is never served to the
 * person it names -- a block is a decision about a pack, not a verdict handed
 * to somebody.
 */
export type PackBlock = { github_uid: number, 
/**
 * Absent for a uid that has never signed in here.
 */
login?: string, reason?: string, blocked_by: number, 
/**
 * Who decided it, by name where the mirror knows it.
 */
blocked_by_login?: string, blocked_at: number, };
