// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PackSummary = { pack_id: string, display_name: string, tagline: string, minecraft_version: string, latest_pack_version: string, tags: Array<string>, featured: boolean, 
/**
 * Square pack icon. Renders in BrowsePackCard avatar slot +
 * BrowsePackDetail hero on the launcher.
 */
icon_url: string | null, 
/**
 * Wide hero image. Renders behind BrowsePackDetail hero text;
 * falls back to the launcher's mirror gradient when absent.
 */
banner_url: string | null, 
/**
 * Optional marketing screenshots. Rendered in a horizontal
 * scroller on BrowsePackDetail when non-empty.
 */
gallery_urls: Array<string>, 
/**
 * Long-form CommonMark description for the BrowsePackDetail
 * About section. HTML is not parsed by the launcher.
 */
description_md: string | null, };
