// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeclaredAsset } from "./DeclaredAsset";
import type { DeclaredMod } from "./DeclaredMod";
import type { LoaderSpec } from "./LoaderSpec";
import type { PackMeta } from "./PackMeta";
import type { PackTier } from "./PackTier";
import type { Visibility } from "./Visibility";

/**
 * Admin-authored declaration of a pack. The build step turns this into a wire
 * `PackManifest` by resolving each source against Modrinth or the local
 * storage tree. Distinct from `PackManifest` because authoring does not
 * require admin to hand-write `sha1` and `size_bytes` for Modrinth sources --
 * those are looked up at build time.
 */
export type PackConfig = { pack_id: string, display_name: string, tagline: string, minecraft_version: string, loader: LoaderSpec, java_major: number, 
/**
 * Human semver-ish line for the build version string
 * (`SNAPSHOT-<version>-<date>`). Pre-1.0 packs sit at `0.0.x`; the operator
 * bumps it rarely. Absent -> `0.0.0`. The date + same-day counter advance
 * automatically, so this is the only version part anyone hand-edits.
 */
version?: string, tags: Array<string>, featured: boolean, mods: Array<DeclaredMod>, assets: Array<DeclaredAsset>, pack_meta: PackMeta, 
/**
 * GitHub uid of the pack owner. Official packs are owned by the operator;
 * community packs by their member. Server-controlled -- never taken from a
 * client config edit (see `put_pack_config`).
 */
owner: number, tier: PackTier, visibility: Visibility, 
/**
 * Source pack id when this pack is a fork; absent otherwise.
 */
fork_of?: string, };
