// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffEntry } from "./DiffEntry";
import type { DiffToggle } from "./DiffToggle";
import type { DiffUpdate } from "./DiffUpdate";
import type { FieldChange } from "./FieldChange";

/**
 * The change summary between two builds, `from` -> `to`. Entries are matched
 * by stable identity (Modrinth project, else the curator slug, else the
 * filename), so a version bump that renames the jar still reads as an update
 * rather than a remove + add.
 */
export type PackDiff = { schema_version: number, pack_id: string, from: string, to: string, 
/**
 * False when the two builds share a content fingerprint (a relabel).
 */
content_changed: boolean, loader?: FieldChange, minecraft?: FieldChange, java?: FieldChange, mods_added: Array<DiffEntry>, mods_removed: Array<DiffEntry>, mods_updated: Array<DiffUpdate>, mods_toggled: Array<DiffToggle>, assets_added: Array<DiffEntry>, assets_removed: Array<DiffEntry>, assets_updated: Array<DiffUpdate>, };
