// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A fork offered back to the pack it came from.
 *
 * The proposed state is not stored here: it is `source_commit` in
 * `source_pack`, which is already an immutable snapshot with an author, a
 * message and a parent. This row is the request around it.
 */
export type Proposal = { id: number, 
/**
 * The pack being asked to take the change.
 */
target_pack: string, 
/**
 * The fork the change lives in.
 */
source_pack: string, 
/**
 * The commit in `source_pack` being offered.
 */
source_commit: string, by_uid: number, 
/**
 * The proposer's login, where they have signed in here.
 */
by_login?: string, message: string, 
/**
 * `open` | `merged` | `declined` | `withdrawn`.
 */
status: string, created_at: number, decided_at?: number, decided_by?: number, 
/**
 * What the merge wrote into the target, so a settled proposal points at
 * what it became and not only at what it asked for.
 */
merged_commit?: string, };
