// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One dependency a save would pull in, answered before the save happens.
 */
export type PulledPreview = { filename: string, 
/**
 * Where the mirror would take it from: `modrinth` or the mirror's own cache.
 */
source: string, 
/**
 * The declared mods that require it, by filename. A library two mods need
 * names both, so removing one does not imply the library leaves.
 */
needed_by: Array<string>, };
