// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VersionRow } from "./VersionRow";

/**
 * One release (version node) of a mod for the management view: its version
 * number + channel, the provenance, and the files (artifacts) grouped under it.
 * Files carry the loader/mc facets; the release carries version + channel.
 */
export type ReleaseRow = { release_id: number, version_number: string, channel: string, source: string, files: Array<VersionRow>, };
