// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Single edge in a mod's dependency DAG. [filename] must match a
 * mods[] entry's filename in the same manifest. [version_range]
 * follows Maven-style range syntax (`>=4.0`, `[1.0,2.0)`); null
 * means "any version present is acceptable". [optional] = true
 * means the consumer works without the dep but works better with
 * it -- launcher shows it greyed-out in the dep tree.
 */
export type Requirement = { filename: string, version_range: string | null, optional: boolean, };
