// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A present mod that is depended-on but marked optional.
 */
export type RequiredHint = { filename: string, modid?: string, needed_by: Array<string>, };
