// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActiveConflict } from "./ActiveConflict";
import type { CapabilityOverlap } from "./CapabilityOverlap";
import type { LoaderMismatch } from "./LoaderMismatch";
import type { MissingDep } from "./MissingDep";
import type { RequiredHint } from "./RequiredHint";
import type { VersionIssue } from "./VersionIssue";

/**
 * The outcome of resolving a pack against the registry graph. Arrays are empty
 * when clean; `missing` and `conflicts` are the blocking problems, the rest are
 * advisory. All lists are sorted for a stable render.
 */
export type ResolveReport = { declared_mods: number, 
/**
 * How many declared jar mods mapped to a registry identity (the rest are in
 * `unresolved` and could not be reasoned about).
 */
resolved_mods: number, 
/**
 * A hard dependency no present mod satisfies -- the pack would crash.
 */
missing: Array<MissingDep>, 
/**
 * Two present mods the graph says cannot run together.
 */
conflicts: Array<ActiveConflict>, 
/**
 * A capability more than one present mod provides -- usually redundant, and
 * the two may fight over the same hook.
 */
overlaps: Array<CapabilityOverlap>, 
/**
 * A present dependency whose shipped version sits outside a requirer's
 * declared window.
 */
version_issues: Array<VersionIssue>, 
/**
 * A present mod that another present mod requires but that the pack marks
 * optional -- it should be required.
 */
required_hints: Array<RequiredHint>, 
/**
 * Declared artifacts this pack's loader cannot run, with nothing present to
 * bridge them -- they will not load at all (#50).
 */
loader_mismatch: Array<LoaderMismatch>, 
/**
 * Foreign-loader artifacts a present bridge may carry. Left unjudged on
 * purpose: a connector runs some of another loader's mods and not others, so
 * neither "fine" nor "broken" is a claim that can be made here.
 */
loader_unverified: Array<LoaderMismatch>, 
/**
 * Declared jar mods with no registry identity yet (an un-harvested upload,
 * or a Modrinth pin the mirror has not seen). Left unjudged, listed so the
 * operator knows coverage was partial.
 */
unresolved: Array<string>, 
/**
 * How many version windows could not be checked because a version string was
 * not plainly comparable (a classifier suffix, an embedded MC prefix).
 */
version_windows_unchecked: number, };
