// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Curator-authored mapping of mod filename to role string.
 * Loaded from a TOML file via [`load_role_table`].
 */
export type RoleTable = { roles: { [key in string]?: string }, };
