// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One mod a server says it runs.
 */
export type ServerMod = { modid: string, version: string, };
