// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerMod } from "./ServerMod";

/**
 * What a server advertised, and what it did not.
 */
export type ServerStatus = { 
/**
 * The server's own version string, as shown in the multiplayer list.
 */
version: string, 
/**
 * The mod list the server advertises. Empty for a vanilla server, and also
 * empty for a modded one configured not to advertise -- `advertises_mods`
 * separates those two, because "no mods" and "will not say" are different
 * answers and a spoof built from the second would be a guess.
 */
mods: Array<ServerMod>, advertises_mods: boolean, };
