// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerEntry = { schema_version: number, server_id: string, pack_id: string, display_name: string, tagline: string, description_md: string, banner_url: string, gallery_urls: Array<string>, tags: Array<string>, discord_url?: string, website_url?: string, 
/**
 * Where the server actually is, `host` or `host:port`. Absent on entries
 * written before the field existed -- and absent means the mirror cannot
 * ask the server anything, which is why it is worth filling: the handshake
 * mod list a pack has to advertise comes from the server itself (#110).
 */
address?: string, owner_display: string, motd_override?: string, founded_at?: string, featured: boolean, };
