// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerEntry = { schema_version: number, server_id: string, pack_id: string, display_name: string, tagline: string, description_md: string, banner_url: string, gallery_urls: Array<string>, tags: Array<string>, discord_url?: string, website_url?: string, owner_display: string, motd_override?: string, founded_at?: string, featured: boolean, };
