// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Axis A -- which side a mod's code executes on.
 */
export type SideClass = "client" | "server" | "both";
