// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One Modrinth-vs-bytecode side conflict on a declared mod.
 */
export type SideDisagreement = { filename: string, 
/**
 * The winning side per the Modrinth environment flags.
 */
modrinth_side: string, 
/**
 * What the bytecode derivation concluded instead.
 */
bytecode_side: string, };
