// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a claim came from, so a spoof is traceable to a server that actually
 * gave this answer rather than being an anonymous assertion. Also what makes
 * staleness answerable: ask the same server again and compare.
 */
export type SpoofSource = { host: string, port: number, 
/**
 * The server version string it reported alongside the list.
 */
server_version: string, asked_at: string, };
