// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpoofMod } from "./SpoofMod";

/**
 * The file itself. Field order matters to nobody, but the order of `mods` is
 * preserved on the wire, so it is preserved here: the list is the server's,
 * in the server's order.
 */
export type Spoof = { mods: Array<SpoofMod>, };
