// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Spoof } from "./Spoof";

/**
 * What a pack claims, what its server wants, and the difference.
 */
export type SpoofReport = { 
/**
 * The claim the pack ships. Absent when it ships none, which is the
 * ordinary case -- most packs match their server without help.
 */
shipped?: Spoof, 
/**
 * What the server advertises now. Absent when the pack names no server,
 * the server has no address recorded, or it could not be reached.
 */
current?: Spoof, server_id?: string, 
/**
 * The address actually asked, when one was.
 */
asked?: string, 
/**
 * Why the server was not asked, or why its answer yielded nothing. Absent
 * when it was asked and answered: then an empty `drift` means they agree,
 * which is the one case worth telling apart from every kind of silence.
 */
unasked?: string, 
/**
 * Empty when they agree, or when there was nothing to compare.
 */
drift: Array<string>, };
