// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One claimed mod. `id` is the Forge mod id the server named, carried through
 * untouched -- it came from the server's own handshake, so it already is what
 * the server expects, and normalising it could only break a match.
 */
export type SpoofMod = { id: string, version: string, };
