// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Display } from "./Display";
import type { SourceDecl } from "./SourceDecl";

export type SubstituteEntry = { source: SourceDecl, display: Display | null, };
