// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An account stopped by the mirror's operators, and why.
 *
 * The reason is written for the person it names: they read it when they try to
 * write and on their own page, which is what makes it something they can
 * answer rather than a door that shuts silently.
 */
export type Suspension = { reason?: string, by_uid: number, by_login?: string, at: number, };
