// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One thing said on a thread.
 *
 * A moderated comment is hidden, not deleted: that something was said and
 * taken down is itself part of the record, and a hole in a discussion reads
 * worse than a marked gap. The body of a hidden comment never leaves the
 * mirror -- the reader is told there was one and who took it down.
 */
export type ThreadComment = { id: number, by_uid: number, by_login?: string, 
/**
 * Absent when the comment is hidden.
 */
body?: string, hidden: boolean, created_at: number, };
