// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something said about a pack: a report, or a fork offered back.
 *
 * One shape for both because they differ only in what opens them and how they
 * settle. A proposal names the state it offers (`source_pack` /
 * `source_commit`), which is a commit rather than "whatever that fork says
 * today", so what a reviewer reads cannot move while they read it. An issue
 * leaves those empty and is simply a thing somebody asked for.
 */
export type Thread = { id: number, pack_id: string, 
/**
 * `issue` | `proposal`.
 */
kind: string, title: string, body: string, by_uid: number, by_login?: string, 
/**
 * An issue is `open` or `closed`; a proposal is `open`, `merged`,
 * `declined` or `withdrawn`.
 */
status: string, source_pack?: string, source_commit?: string, 
/**
 * What a merge wrote into the target, so a settled proposal points at what
 * it became and not only at what it asked for.
 */
merged_commit?: string, created_at: number, decided_at?: number, decided_by?: number, 
/**
 * How many comments are on it, so a list can say so without reading them.
 */
comments: number, };
