// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Thread } from "./Thread";
import type { ThreadComment } from "./ThreadComment";

/**
 * One thread and everything said on it.
 */
export type ThreadView = { thread: Thread, comments: Array<ThreadComment>, };
