// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A jar on disk with no registry identity yet (harvest could not derive a
 * modid/Modrinth id). The authoring UI lists these so the operator can assign
 * each a mod + release + facets instead of it vanishing into the cache.
 */
export type UnassignedJar = { sha1: string, size_bytes: number, };
