// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Suspension } from "./Suspension";

/**
 * A registered user, for the operator's user-management view.
 */
export type UserRow = { github_uid: number, login: string, role: string, created_at: number, last_login_at: number, 
/**
 * Present while the account is stopped from putting anything on the mirror.
 */
suspension?: Suspension, };
