// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of cross-referencing a `PackConfig` against an SC archive by
 * mod filename. `missing_in_config` (in the archive but not declared)
 * would break the FML handshake; `extra_in_config` (declared but not in
 * the archive) is expected when the curator adds mods on top.
 */
export type ValidateReport = { sc_mod_count: number, declared_mods: number, declared_assets: number, matched: number, missing_in_config: Array<string>, extra_in_config: Array<string>, };
