// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A present dependency shipping a version outside a declared window.
 */
export type VersionIssue = { target: string, filename: string, present_version: string, required_range: string, needed_by: Array<string>, };
