// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Q3: one version of a mod, with every loader it targets (`any` for a
 * loader-agnostic jar) and the Minecraft versions it was published for.
 */
export type VersionRow = { version: string, targets: Array<string>, mc_versions: Array<string>, sha1: string, size_bytes: number, filename: string | null, source: string, 
/**
 * True when the artifact's bytes are in the mirror's local cache, so it can
 * be re-added as a self-hosted `smrt_cache` source. Set by the handler
 * against the live cache inventory (not stored in the registry).
 */
cached: boolean, 
/**
 * Modrinth identity, when the artifact is one. Lets the panel re-add a
 * not-locally-cached Modrinth mod as a real Modrinth source.
 */
modrinth_project_id: string | null, modrinth_version_id: string | null, };
