// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Q3: one version of a mod, with every loader it targets (`any` for a
 * loader-agnostic jar) and the Minecraft versions it was published for.
 */
export type VersionRow = { version: string, targets: Array<string>, mc_versions: Array<string>, sha1: string, size_bytes: number, filename: string | null, source: string, };
