// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Release channel of a pack version, derived from the version string itself:
 * the panel's build pipeline stamps work-in-progress builds as
 * `SNAPSHOT-<semver>-<date>[.N]`, while operator-published versions are bare
 * `YYYY.MM.DD[.N]` strings. Launchers use this to default users onto releases
 * and label snapshots explicitly.
 */
export type VersionChannel = "release" | "snapshot";
