// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Release channel of a pack build -- the Modrinth `version_type` vocabulary,
 * shared with mod releases in the registry so the whole mirror speaks one
 * dialect. Stored on the manifest as its own field (`channel`); the version
 * string carries no channel semantics.
 */
export type VersionChannel = "release" | "beta" | "alpha";
