// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Publication state. Only `published` packs reach the public listing; `draft`
 * is work-in-progress, `unlisted` is reachable by direct id but off the catalog.
 */
export type Visibility = "draft" | "unlisted" | "published";
